In [35]:
import pandas as pd
from sklearn.model_selection import train_test_split
import seaborn as sns
from sklearn.linear_model import LinearRegression

In [36]:
df=pd.read_csv("Student_Performance.csv")

## Data is Linear or Non Linear

In [37]:
df.corr(numeric_only=True)

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Performance Index
Hours Studied,1.000000,-0.012390,0.001245,0.017463,0.373730
Previous Scores,-0.012390,1.000000,0.005944,0.007888,0.915189
Sleep Hours,0.001245,0.005944,1.000000,0.003990,0.048106
Sample Question Papers Practiced,0.017463,0.007888,0.003990,1.000000,0.043268
Performance Index,0.373730,0.915189,0.048106,0.043268,1.000000

In [38]:
x=df.drop(columns='Performance Index')
y=df['Performance Index']

In [39]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,train_size=0.8,random_state=42)

In [40]:
xtrain

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
9254,5,49,No,7,5
1561,2,48,Yes,7,6
1670,2,81,No,7,2
6087,2,46,No,6,1
6669,8,47,No,9,0
...,...,...,...,...,...
5734,8,50,Yes,6,6
5191,4,68,No,9,3
5390,9,48,No,7,6
860,1,47,No,9,0
7270,2,46,No,6,6

In [41]:
xtest

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
6252,5,69,No,8,2
4684,2,46,Yes,4,8
1731,7,56,Yes,7,5
4742,6,42,Yes,8,5
4521,7,53,No,4,6
...,...,...,...,...,...
6412,2,70,No,7,3
8285,4,79,No,9,3
7853,2,40,Yes,7,2
1095,3,83,No,7,5
6929,5,60,No,8,4

## Model Creation

In [42]:
model = LinearRegression()

## Model Training

In [1]:
model.fit(xtrain,ytrain) # learns the pattern from input and output

NameError: name 'model' is not defined